### ISSUE TITLE
Update samples to reflect with current APIs

### ISSUE THREAD

**Issue by modotte** [phadej/github#466] opened 2021-11-01 11:23 UTC
Hi. I was trying to run the sample from README.md and other code from `samples/`, but I failed to build them and I believe many of these samples are not up to date with the current package's API.

Thanks for reviewing. :slightly_smiling_face:

**Comment by phadej** [comment] 2021-11-01 11:26
A moral duplicate of https://github.com/phadej/github/issues/167

At this point i'm thinking of simply removing non-tested samples, as I don't think I'll do anything to them.

**Closed by phadej** 2021-11-01 11:26 UTC
